#配置服务器信息,指定端口号
server:
  port: 9527

spring:
  application:
    name: mybais-demo
  datasource:
    url: jdbc:sqlserver://61.129.57.232:1433;databasename=sanquan_dmprod0303
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sanquan
    password: sanquan123

#mybatis依赖
mybatis:
  type-aliases-package: com.demand.driven.entity
  mapper-locations: classpath:mapper/*.xml
  configuration.map-underscore-to-camel-case: true

logging:
  level:
    web: debug

is_dev_env: false

app_config:
  appIdKey: 10016
  signKey: sanquan123




